# Generated by Django 5.1.3 on 2024-12-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='date',
            field=models.CharField(default='月曜日', max_length=10),
        ),
        migrations.AddField(
            model_name='subject',
            name='table',
            field=models.CharField(default='1限目', max_length=10),
        ),
    ]
